### ISSUE TITLE
Lists does not save correctly

### ISSUE THREAD

**Issue by Leymooo** [timvisee/yaml-wrapper#3]
```java
        YamlConfiguration configuration = new YamlConfiguration();
        configuration.set("list", Arrays.asList("1","2"));
        configuration.set("list-2", Arrays.asList("127.0.0.1", "192.168.88.1"));
        System.out.println(configuration.saveToString());
```
Output will
```
list:
    list:
    - '1'
    - '2'
list-2:
    list-2:
    - 127.0.0.1
    - 192.168.88.1
```

PoC:
![image](https://user-images.githubusercontent.com/8667294/53034845-cbb90480-347c-11e9-8919-5cbaaee1d2d9.png)
